
export const FAVORITE_CREATE_REQUEST = 'FAVORITE_CREATE_REQUEST';
export const FAVORITE_CREATE_SUCCESS = 'FAVORITE_CREATE_SUCCESS';
export const FAVORITE_CREATE_FAIL = 'FAVORITE_CREATE_FAIL';
export const FAVORITE_CREATE_RESET = 'FAVORITE_CREATE_RESET';

export const FAVORITE_LIST_MY_REQUEST = 'FAVORITE_LIST_MY_REQUEST';
export const FAVORITE_LIST_MY_SUCCESS = 'FAVORITE_LIST_MY_SUCCESS';
export const FAVORITE_LIST_MY_FAIL = 'FAVORITE_LIST_MY_FAIL';
export const FAVORITE_LIST_MY_RESET = 'FAVORITE_LIST_MY_RESET';